import ServicesPage from "./services-page";

export const metadata = {
  title:
    "AC Services | Installation, Repair, Maintenance & Rental | EREngineers",
  description:
    "Professional AC installation, repair, maintenance, gas refilling, relocation & rental services in Sri Lanka. Certified technicians, same-day service, free quotes. Call 077 123 4567",
  keywords: [
    "EREngineers",
    "ER Engineers",
    "AC services Sri Lanka",
    "air conditioning services",
    "AC installation Colombo",
    "AC repair near me",
    "AC rental near me",
    "AC maintenance service",
    "AC gas refilling",
    "AC relocation service",
    "AC rental Sri Lanka",
    "portable AC rental",
    "split AC installation",
    "cassette AC repair",
    "HVAC services Sri Lanka",
    "air conditioner service",
    "AC technician Colombo",
    "emergency AC repair",
    "same day AC service",
    "best AC service Sri Lanka",
    "affordable AC repair",
    "AC service Moratuwa",
    "AC service Colombo",
    "24/7 AC repair",
    "commercial AC service",
    "residential AC installation",
    "AC filter cleaning",
    "AC gas top up",
    "AC compressor repair",
    "AC fan motor replacement",
    "AC thermostat repair",
    "AC duct cleaning",
    "AC chemical wash",
    "window AC service",
    "central AC repair",
    "VRV AC maintenance",
    "inverter AC repair",
    "AC annual maintenance contract",
    "AC service near me",
    "best AC technicians",
    "certified AC repair",
    "AC service warranty",
    "free AC consultation",
  ].join(", "),
  openGraph: {
    title:
      "Professional AC Services in Sri Lanka | Expert Installation, Repair & Rental | EREngineers",
    description:
      "Get professional AC installation, repair, maintenance, gas refilling, relocation & rental services. Certified technicians, same-day service, best prices. Free consultation! Call 077 123 4567",
    url: "https://www.erengineers.lk/services",
    type: "website",
    siteName: "EREngineers",
    locale: "en_US",
    images: [
      {
        url: "https://erengineers.com/images/ere-logo.jpg",
        width: 1200,
        height: 630,
        alt: "EREngineers Professional AC Services",
      },
    ],
    emails: "info@erengineers.com",
    phoneNumbers: "+94771234567",
    countryName: "Sri Lanka",
  },
  twitter: {
    card: "summary_large_image",
    title: "Professional AC Services in Sri Lanka | EREngineers",
    description:
      "Expert AC installation, repair, maintenance & rental services. Certified technicians, same-day service, free quotes!",
    images: ["https://www.erengineers.lk/images/ere-logo.jpg"],
    site: "@erengineers",
    creator: "@erengineers",
  },
  alternates: {
    canonical: "https://www.erengineers.lk/services",
  },
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  category: "AC Services",
  authors: [{ name: "EREngineers", url: "https://www.erengineers.lk" }],
  creator: "EREngineers",
  publisher: "EREngineers",
};

export default ServicesPage;
